- src/components/molecules/UiScale/UiScale.vue
in Browse mode, “Mild” and “Unbearable” are read after selecting a value so it may be confusing for screen reader users.
> feat(accessibility): hide mild and unbearable buttons from screen readers

- .unit-test-results.json
- src/components/atoms/UiRange/UiRange.vue
- src/components/molecules/UiDropdown/_internal/UiDropdownItem.vue
- src/components/molecules/UiNotification/UiNotification.vue
- src/components/molecules/UiRating/UiRating.stories.js
- src/components/molecules/UiRating/UiRating.vue
- src/components/molecules/UiScale/UiScale.stories.js
- src/components/molecules/UiScale/UiScale.vue
- src/components/molecules/UiSwitch/_internal/UiSwitchControl.vue
- src/components/organisms/UiAccordion/_internal/UiAccordionItem.vue
- src/components/organisms/UiControls/UiControls.vue
- src/components/organisms/UiDatepicker/UiDatepicker.vue
- src/components/organisms/UiModal/UiModal.vue
- src/components/organisms/UiMultipleAnswer/UiMultipleAnswer.stories.js
- src/components/templates/UiMessage/UiMessage.stories.js
Props in Vue allow setting `default` value. In many cases this will be enough. But not for settings, transitions objects. 
`translation` in UiScale component.
```js
const props = defineProps({
translation: {
type: Object,
default: () => ({
label: 'Pain scale',
mild: 'Mild',
unbearable: 'Unbearable',
}),
},
})
```
To set `label` user should set other values `mild` and `unbearable`.
To solve this issue I add proxy for props call `defaultProxy`
```js
const props = defineProps({
translation: {
type: Object,
default: () => ({
label: 'Pain scale',
mild: 'Mild',
unbearable: 'Unbearable',
}),
},
})
const defaultProps = computed(() => ({
translation: {
label: 'Pain scale',
mild: 'Mild',
unbearable: 'Unbearable',
...props.translation,
},
}));
```
To set `label` user can pass only the `label` value. …
> refactor: use defaultProps as proxy for some props

- package.json
Close #33 
- fix the problem with incorrect export of types and interfaces by removing `tsc` from the script` check: types`
> fix: remove tsc from check:types script

- docs/components/Code.jsx
- docs/contributing-guide/css-var-deep-dive.stories.mdx
- docs/development-guide/theme-configuration.stories.mdx
- docs/development-guide/working-with-breakpoints.stories.mdx
- docs/releases/v0.2.x/v0.2.0.stories.mdx
- docs/releases/v0.5.x/v0.5.0/migration-guide.stories.mdx
- docs/releases/v0.5.x/v0.5.1/migration-guide.stories.mdx
- src/components/molecules/UiHeader/UiHeader.mdx
- src/components/molecules/UiHeader/UiHeader.stories.js
- src/components/molecules/UiHeader/UiHeader.stories.scss
- src/components/molecules/UiInteractiveSvg/UiInteractiveSvg.mdx
- src/components/molecules/UiInteractiveSvg/UiInteractiveSvg.stories.scss
- src/components/molecules/UiLoader/UiLoader.mdx
- src/components/molecules/UiLoader/UiLoader.stories.scss
- src/components/organisms/UiMenu/UiMenu.mdx
- src/components/organisms/UiMenu/UiMenu.stories.js
- src/components/organisms/UiMenu/UiMenu.stories.scss
Close
* Add `Code` to Storybook Doc Blocks
* Use `Code` to scrap `*.stories.scss` and display SCSS
* Use `Code` in docs instead `'''scss'''` to support highlighting
```scss
//.stories.scss
// <Code id="header-custom-brand">
.header-custom-brand {}
// </Code>
```
```jsx
//.mdx
import scss from '*.stories.scss?raw'
...
<Code
id="header-custom-brand"
code={scss}
/>
```
**Before**
**After**
> feat: code docs block

- src/components/atoms/UiCheckbox/UiCheckbox.vue
- src/components/atoms/UiRadio/UiRadio.vue
- src/components/molecules/UiRating/UiRating.stories.js
Close #67 
* UiCheckbox and UiRadio `<input/>` handle only `focus` and `blur` listeners. Other listeners are passed to the label.
`<input/>` is visual-hidden and it handle only `focus` and `blur` listeners 
**UiScale**
**UiRating**
> fix: hover action in UiRating and UiScale it doesn't works

- .husky/pre-push
- package.json
I think pre-push is not the best place to run these scripts :( My idea fails. Now it should be better. 
* `test` on pre-push will prevent push code with failing tests to the repository. 
* `create:index`, `create:icons-list`, and `test:generate-output` can be run before release to keep it updated. 
* `create:index` will be run after `create:component`
> refactor: run only test on pre-push

- src/utilities/directives/focus-trap/helpers.js
helper for focus-trap skip elements with negative `tabindex`
> fix: elements with negative tabindex will be recognized as focusable

- index.ts
- scripts/create-index.mjs
Closes #85 
All necessary types declared in components are re-exported inside `index.ts` file
- Instead of using a direct path like:
import { UiMultipleChoices } from '@infermedica/component-library''
import type { MultipleChoicesOption } from '@infermedica/component-library/src/components/organisms/UiMultipleChoices/UiMultipleChoices.vue'
- It's now possible to use:
`import { UiMultipleChoices, type MultipleChoicesOption } from '@infermedica/component-library'`
> feat: add export types in index

- src/components/organisms/UiMultipleChoices/UiMultipleChoices.stories.js
- src/components/organisms/UiMultipleChoices/_internal/UiMultipleChoicesItem.vue
Closes #132   
- Prevent shrinking multiple choices item radio buttons
- Fixing incorrect mobile padding override for `.ui-multiple-choices-item__option-content` element.
> fix: shrinking multiple choices item radio buttons

- src/composable/useLink/index.ts
Closes #130 
- Set relative import instead of aliased in `useLink` composable
> fix: useLink composable uses aliased import

- src/components/organisms/UiCard/UiCard.stories.js
- src/components/organisms/UiCard/UiCard.vue
Closes #129  
- Remove `align-items: center` from `.ui-card__triage`  element
- Set correct padding for `.ui-card--modern .ui-card__triage`  element (16px for mobile, and 32px for tablet)
> fix: remove align-items: center from card triage element

- src/components/organisms/UiMultipleChoices/_internal/UiMultipleChoicesItem.vue
Close #156 
- fix UiMultipleChoicesItem styles on Safari; Paddings and borders are
> fix: broken mobile layout if UiMultipleChoices on Safari

- src/components/molecules/UiRating/UiRating.vue
Close #180 
* show focus for tab navigation
* focus selected value (pass name in right way)
> fix: missing focus outline in UiRating

- src/components/organisms/UiSimpleQuestion/UiSimpleQuestion.vue
fix: define missing `tileItemAttrs` slot prop for `UiSimpleQuestion` component.
> fix: missing `tileItemAttrs` slot prop for `UiSimpleQuestion`

- src/components/organisms/UiMultipleChoices/UiMultipleChoices.spec.js
- src/components/organisms/UiMultipleChoices/_internal/UiMultipleChoicesItem.vue
Closes #198 
- Pass `name` attribute to `input-attrs` instead of radio wrapper
https://github.com/infermedica/component-library/assets/17556031/550ccf84-ff76-464a-950f-9d2a9b1ddeb2
> fix: missing name attribute for multiple choices item inputs

- src/components/molecules/UiScale/UiScale.vue
Closes #208 
- Pass `name` attribute to `input-attrs` instead of radio wrapper
https://github.com/infermedica/component-library/assets/17556031/f8a7ff80-2b01-4deb-a675-2b82683f2807
> fix: missing name attribute for inputs in UiScale

- src/components/organisms/UiDatepicker/UiDatepicker.spec.js
- src/components/organisms/UiDatepicker/_internal/UiDatepickerDayInput.vue
- src/components/organisms/UiDatepicker/_internal/UiDatepickerMonthInput.vue
- src/components/organisms/UiDatepicker/_internal/UiDatepickerYearInput.vue
Closes #201 
- Handle update of input only by `@input` events instead of a combination of `@input` and `v-model` that cause incorrect order of value assignments
https://github.com/infermedica/component-library/assets/17556031/d9bc8d37-275c-42f1-98de-d3878d35ef8f
> fix: auto skip to next date field

- src/components/organisms/UiTabs/UiTabs.vue
- src/components/organisms/UiTabs/_internal/UiTabsItem.vue
- src/types/utils.ts
Closes #202 
- **Added better RWD support** When resizing tabs component underline was not updated.
- **Added vertical tabs support**. When we had more then one row of tabs underline was not displayed correctly.
- **Fixed issue with incorrect underline position** Underline pseudo element was not displayed in the right place when the fist tab was not selected by default.
https://github.com/infermedica/component-library/assets/89569524/9a324a51-3330-4ae4-8739-4a6737d3b447
@pspaczek
> fix: incorrect position of underline element in UiTabs

- src/components/organisms/UiSidePanel/UiSidePanel.vue
Close #200, #207
I removed `v-keyboard-focus` everything works fine. This action shouldn't change anything for focus visibility. 
Later I will check why `v-keyboard-focus` make this issue.
> fix: keyboard navigation works incorrectly in UiSidePanel

- src/components/molecules/UiRating/UiRating.spec.js
- src/components/molecules/UiRating/UiRating.vue
Closes #220 
- Use translation from passed props instead of constant computed property
> fix: translations for UiRating component

- src/components/molecules/UiStepper/_internal/UiStepperStep.vue
Closes #222 
I decided to revert the change and have all steps become UiButtons. Not only it fixes the issue, but I think inactive buttons are overall more descriptive than switching between text and button element.
> fix: inactive Steps violate a11y Contrast rules

- src/components/molecules/UiStepper/UiStepper.stories.js
- src/components/molecules/UiStepper/_internal/UiStepperStep.vue
- fix: undefined property in UiStepperStep slot
- chore: remove outdated UiStepperStep story
Fixed warnings during the render of UiStepper:
> fix: undefined property in UiStepperStep slot

- package.json
Chunks produced by Webpack and Vite for @infermedica/component-library are excessively large due to suboptimal tree shaking.
Configuring the `"sideEffects": ["*.vue"]` property in package.json results in a significant reduction in chunk size.
For clarity, I've set up two sandboxes to demonstrate the difference in chunk sizes before and after the proposed changes.
Execute the `pnpm build` command to generate the see output.
**Before changes**: https://stackblitz.com/edit/vitejs-vite-v6mkjt
```
dist/index.html                   0.45 kB │ gzip:  0.30 kB
dist/assets/index-9f343985.css  196.77 kB │ gzip: 21.06 kB
dist/assets/index-46952e10.js    57.29 kB │ gzip: 22.98 kB
```
**After changes**: https://stackblitz.com/edit/vitejs-vite-bdewkc
```
dist/index.html                  0.45 kB │ gzip: …
```
> fix: improve tree shaking and reduce chunk sizes

- src/components/organisms/UiMenu/_internal/UiMenuItem.vue
- src/components/organisms/UiMenu/_internal/UiMenuItemSuffix.vue
- change `ui-menu-item__button`'s `border-radius` according to the design;
- change default icon to smaller one - from `checkmark` to `present`
[Link to the newest MGP Component Library](https://www.figma.com/file/2p8nMM7W88FU6r0kA52fAA/MGP-Component-Library?type=design&node-id=3-12660&mode=design&t=AUQplhjDmsNUAgLb-4)
> fix: adjust UiMenuItem to the newest MGP Component Library design:

- src/components/molecules/UiLoader/UiLoader.vue
- src/components/molecules/UiLoader/_internal/UiLoaderNativeTransition.vue
- src/components/molecules/UiLoader/_internal/UiLoaderTransition.vue
In both cases, we need this `<div/>` to use `<transition/>` because IMO `<transition-group>` is used to other issues than UiLoader. To prevent problems with box model we want to use display: contents to make this div `invisible`.  
After:
Before:
> fix: loaded content with redundant box

- src/components/molecules/UiTile/UiTile.vue
Fixed border radius on Tile component - use new token.
> fix: change button border-radius variable on UiTile according to the newest design

- src/components/atoms/UiButton/UiButton.vue
> fix: TypeScript error in UiButton regarding loaderAttrs.type property

- src/components/organisms/UiMultipleChoices/_internal/UiMultipleChoicesItem.vue
Use H2 as label. With h4 styles on mobile and body-1 on desktop
> fix: change UiMultipleChoicesItem heading fonts according to the newest designs

- src/components/molecules/UiFormField/UiFormField.mdx
- src/components/molecules/UiFormField/UiFormField.stories.js
- src/components/molecules/UiFormField/UiFormField.vue
- src/components/molecules/UiFormField/_internal/UiFormFieldCharacterCounter.vue
UiFormField allows to display character counter. 
UiFormField has new props:
* value
* hasCharacterCounter
* characterCounterAttrs
UiFormField has a new emit:
* error: string | null
How to handle error
```
const handleErrorEmit = (error) => {
if (error === 'max length exceeds') {
errorMsg.value = 'Use max 240 characters';
return;
}
errorMsg.value = '';
};
```
> feat: add character counter to UiFormField

- src/components/organisms/UiCard/UiCard.vue
Ui-icon is always set to emergency unless we provide the iconTriageAttrs. Deleted the default value for this prop.
> Fix: UiCard won't change icon unleass iconTriageAttrs are provided.

- index.ts
- package.json
- scripts/create-index.mjs
- src/composable/index.ts
This pull request removes the `exports` field from the `package.json` file to ensure compatibility with Vite, which currently does not support this feature. Additionally, the PR refactors the export structure in `index.ts` and adds a new index file for composables.
- Removed `exports` section from `package.json`.
- Added new exports in `index.ts` for utilities, composables, and component types.
- Modified `scripts/create-index.mjs` to reflect the new export structure.
- Added a new `src/composable/index.ts` file for exporting composable utilities.
> feat: remove `exports` from package.json

- src/components/molecules/UiDropdown/_internal/UiDropdownItem.vue
This PR addresses an alignment issue in the dropdown items. When the text spans more than two lines, the alignment was previously incorrect.
Applied text-align: start to ensure consistent and correct alignment for multiline text.
Before:
After:
> fix: incorrect text alignment in dropdown item

- src/components/molecules/UiStepper/_internal/UiStepperStep.vue
UiStepperStep padding got changed to `--space-12`. Token `--space-10` will be not used in designs.
> fix: change padding in UiStepperStep according to the newest design

- src/components/atoms/UiButton/UiButton.vue
- src/components/molecules/UiTile/UiTile.stories.js
- src/components/molecules/UiTile/UiTile.vue
- src/components/organisms/UiSimpleQuestion/UiSimpleQuestion.stories.js
- src/components/organisms/UiSimpleQuestion/UiSimpleQuestion.vue
- src/components/templates/UiQuestion/UiQuestion.stories.js
- change `UiTile` type to type `button`
- in `UiSimpleQuestion` add role `group` to surround answers in one group
- in `UiQuestion`  and  `UiSimpleQuestion` stories I connected the title of the question with group of answers to enable VoiceOver proper reading
> fix(a11y): tiles as radios in UiSImpleQuestion component

- src/components/organisms/UiDatepicker/_internal/UiDatepickerTabItem.vue
The UiDatepickerTabItem has the wrong border-radius when compared to Figma. It happens because the standard button border-radius is still used for date picker items.
[Storybook](https://component.infermedica.com/?path=/docs/organisms-datepicker--docs)
[Figma](https://www.figma.com/file/2p8nMM7W88FU6r0kA52fAA/MGP-Component-Library?type=design&node-id=2-7371&mode=design&t=zLwkERzEVgtYEyCB-0)
After fix:
> fix: border-radius from button in UiDatepickerTabItem

- src/components/organisms/UiHorizontalPaging/UiHorizontalPaging.stories.js
- src/components/organisms/UiHorizontalPaging/UiHorizontalPaging.stories.scss
- src/components/organisms/UiHorizontalPaging/_internal/UiHorizontalPagingItem.vue
- src/components/organisms/UiSidePanel/UiSidePanel.vue
Before this PR I seated focus before content. In design, the focus should be on the back button.  Now everything is adjusted to:
If back button should be focused after page content open then you need upade component in app directly to this changes -> https://github.com/infermedica/component-library/pull/332/commits/6ede363a92536e486e74f6d4701e0dede52eab53
> fix: different focus order in mobile menu side panel

- src/components/organisms/UiHorizontalPaging/UiHorizontalPaging.vue
- src/main.ts
- vite.config.js
- Remove aliases from the vite. config of Playground App. To detect aliases paths in CL components.
- Use relative path in UiHorizontalPaging
> fix: import by alias in UIHorizontalPaging

- src/components/molecules/UiDropdown/UiDropdown.vue
- src/components/organisms/UiHorizontalPaging/UiHorizontalPaging.stories.js
- src/components/organisms/UiHorizontalPaging/UiHorizontalPaging.stories.scss
- src/components/organisms/UiHorizontalPaging/UiHorizontalPaging.vue
- src/components/organisms/UiHorizontalPaging/_internal/UiHorizontalPagingItem.vue
- src/components/organisms/UiMenu/UiMenu.vue
- src/components/organisms/UiMenu/useMenuItems.js
* Make changes required to build MobileMenu from the design
* Extend the story "As Mobile Menu" to elements from the design
> fix: no way to build MobileMenu from design

- src/components/templates/UiQuestion/UiQuestion.vue
It's crucial for questions to make them available to `submit` them with the UiButton with `type="submit"`.
> fix: unable to submit answer with UiQuestion

- src/components/atoms/UiCheckbox/UiCheckbox.vue
It fixes the bug, which was about having two elements being focused at the same time (visually) because of the checkbox div wrapper. One line of code.
https://github.com/infermedica/component-library/assets/13744352/b668f395-f089-47da-96c2-3dd6b61c011a
https://github.com/infermedica/component-library/assets/13744352/a220e084-6117-4f51-9036-c09fe48c7fdc
Closes #
> fix: focus on the input checkbox persists to another element in the parent wrapper is focused

- .github/workflows/release.yaml
The "Release" GitHub Action will be triggered for closed pull requests from branches prefixed with release/**. The "if-merged" section will execute steps exclusively for merged pull requests.
Closes #383 
We'll automatically release the Component Library once it receives 2 approvals. That's the plan.
> chore: run release GH Action for merged release PRs

- src/components/molecules/UiAlert/UiAlert.vue
UiAlert add alerts attributes as a `props`
An accessibility improvement for  Screen Readers
Not needed
> fix UiAlert attributes for Screen Readers

- src/components/molecules/UiBulletPoints/UiBulletPoints.vue
- src/components/molecules/UiDropdown/UiDropdown.vue
- src/components/organisms/UiControls/UiControls.vue
- src/components/organisms/UiList/UiList.vue
- src/components/organisms/UiMultipleChoices/_internal/UiMultipleChoicesItem.vue
- src/components/organisms/UiSimpleQuestion/UiSimpleQuestion.vue
Filter redundant `label` from `option` object 
Closes #381
> fix: redundant label tag in UiMultipleChoicesItem option UiListItem

- src/components/organisms/UiMultipleChoices/UiMultipleChoices.vue
- src/components/organisms/UiMultipleChoices/_internal/UiMultipleChoicesItem.vue
This pull request addresses the issue of adding focus to the first invalid input in UiMultipleChoices when there is an error status.
Closes #429 
In stories and an application
The solution checked in the application:
https://github.com/infermedica/component-library/assets/37744371/855d6315-734a-4f75-8cd8-8eaf3f386743
> fix: add focus to the first invalid input in UiMultipleChoices

- src/components/molecules/UiScale/UiScale.vue
This PR organizes accessibility topics in UiScale.
Based on this article https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/radiogroup_role#examples when we use `fieldset` and `legend`, `role="radiogoup"` is not necessary. 
Closes #
Use VoiceOver
before, has "grupa" on end
after, without "grupa" on end
> fix: accessibility improvements in UiScale component

- src/components/atoms/UiButton/UiButton.vue
Watch on `props.isLoading` with `immediate` and `once` are mutually exclusive. This PR solves this issue
1. Set `isLoading` https://component.infermedica.com/?path=/docs/atoms-button--docs and you should see no changes.
2. Run this PR and set `isLoading`. I think everything should work well.
> fix: lazy-loaded UiLoader in UiButton

- src/components/molecules/UiScale/UiScale.vue
This prop allows to pass attributes for `legend`
Closes #439 
This attribute is necessary to fix errors reported by EqualWeb plugin
Use the EqualWeb plugin in the story
Before:
After:
> fix: add attributes for legend

- src/components/atoms/UiButton/UiButton.vue
Maintain the default slot the until UiLoader is imported.
Closes #
Button size will change to smallest size before UiLoader is imported.
> fix: jumping UiButton size when importing the loader

- src/components/organisms/UiMultipleChoices/UiMultipleChoices.stories.js
- src/components/organisms/UiMultipleChoices/UiMultipleChoices.vue
1. Simplifies MultipleChoice code and function by removing `invalidInputsRefs` state
2. Changes stories from using `nextTick` too often
`invalidInputsRefs` state was cause of previous bug and after some thoughts, it seems unnecessary. We don't do anything with it until `focusInvalidChoice`, so generating it earlier and updating it doesn't have any value.
Additionally this PR makes `handleSubmit` look identically as in MGP, and moves `nextTick` to happen only once, on mount.
Improves https://github.com/infermedica/component-library/issues/432, although it could already be closed
- [✅] My code follows the style guidelines of this project
- [✅] I have performed a self-review of my code
- [NA] I have made corresponding changes to the documentation
- [✅] My changes generate no new warnings
- …
> refactor: simplify MultipleChoices implementation and improve stories

- src/components/molecules/UiFormField/UiFormField.vue
Character counters are centered relative to the error message. Issue for longes error messages. 
Closes #
Before
After
> fix: character counter centered relative to the error message

- src/utilities/helpers/equal/index.ts
equal() has a problem comparing object with functions. To solve this issue I use "JSON" trick to remove functions
Closes #
> fix: objects with functions cant be equal

- src/components/organisms/UiList/_internal/UiListItemAffix.vue
- src/components/organisms/UiList/_internal/UiListItemPrefix.vue
- src/components/organisms/UiList/_internal/UiListItemSuffix.vue
- src/components/organisms/UiMultipleAnswer/_internal/UiMultipleAnswerItem.vue
UiMultipleAnswareItem can't get UiListItemSuffix template refs to get it size.
Closes #476
> fix: the explanation icon overlaps with a string

- src/components/atoms/UiTextarea/UiTextarea.vue
exposed object in UiTextarea
Closes #
> fix: typo in defineExpose in UiTextarea

- src/components/atoms/UiTextarea/UiTextarea.stories.ts
- src/components/atoms/UiTextarea/UiTextarea.vue
The `min-height` for `textarea` is set when the component is displayed for the first time
Add `overflow-y: scroll` to enable scrolling functionality
Closes #462
> fix: textarea resize issue

- package.json
- pnpm-lock.yaml
- src/components/atoms/UiTextarea/UiTextarea.vue
Bump `vue-tsc` and solve error in `UiTextarea`
Closes #
> fix: error not assignable to type 'StyleValue' in UiTextarea

- src/components/organisms/UiModal/UiModal.stories.js
Add missing input and textarea attrs
Closes #512
> fix: add missing attrs to fix a11y wave errors

- .github/workflows/storybook-manual.yaml
- package.json
- pnpm-lock.yaml
- src/components/molecules/UiPhoneNumber/UiPhoneNumber.stories.ts
- src/components/molecules/UiPhoneNumber/UiPhoneNumber.vue
- src/components/molecules/UiPhoneNumber/_internal/UiPhoneNumberPrefix/UiPhoneNumberPrefix.vue
- src/components/molecules/UiPhoneNumber/_internal/UiPhoneNumberPrefix/UiPhoneNumberPrefixToggle.vue
- src/components/molecules/UiPhoneNumber/helpers/get-phone-codes.spec.ts
- src/components/molecules/UiPhoneNumber/helpers/index.ts
Following on finding from https://gitlab.com/Infermedica/development/triage/symptom-checker-app/-/merge_requests/1721, I decided to replace `i18n-iso-countries` - both to reduce dependency size, but also to make the usage simpler, now it will work with all the languages without requiring the manual import of translations.
- reduce dependencies
- improve user experience
Tested in PhoneNumber stories
- [✅] My code follows the style guidelines of this project
- [✅] I have performed a self-review of my code
- [✅] I have made corresponding changes to the documentation
- [✅] My changes generate no new warnings
- [❌] I have added tests that prove my fix is effective or that my feature works
- [✅] New and existing unit tests pass locally with my changes
> refactor: replace i18n-iso-countries with Intl.DisplayNames

- src/components/molecules/UiPhoneNumber/helpers/index.ts
This _should_ fix an issue with using UiPhoneNumber.
Closes #
- [✅] My code follows the style guidelines of this project
- [✅] I have performed a self-review of my code
- [N/A] I have made corresponding changes to the documentation
- [✅] My changes generate no new warnings
- [N/A] I have added tests that prove my fix is effective or that my feature works
- [✅] New and existing unit tests pass locally with my changes
> fix: change how country-codes-list is imported

- src/components/templates/UiQuestion/UiQuestion.stories.js
- src/components/templates/UiQuestion/UiQuestion.vue
It adds an optional `icon` to the why button in `UiQuestion`. I need this icon because question about sex has this icon:
Closes #
> feat: in UiQuestion add an optional icon for the Why button

- src/components/organisms/UiMultipleAnswer/UiMultipleAnswer.vue
- src/components/organisms/UiMultipleChoices/UiMultipleChoices.vue
- src/styles/variables/typography.scss
- src/utilities/helpers/focus-element/index.ts
- adds emitted `focus:invalidChoice` event to `UiMultipleAnswer` and `UiMultipleChoices`,
- adds `{ preventScroll: true }` to the `el.focus` call in the `focusElement` helper function;
This PR is created in order to make [these changes](https://gitlab.com/Infermedica/development/mgp/modulith/-/merge_requests/2789) working.
[Here's the related Jira issue](https://infermedica.atlassian.net/browse/MGPFE-1905)
> feat: changes focusing invalid choices behavior in UiMultipleAnswer and UiMultipleChoices

- scripts/update-components-api.mjs
Removes `/Users/$USER_NAME/$PATH_TO_FILE` from `sourceFiles` attribute of generated vueDocs.
Without this, every release from a different person than previous release would have changes like [this](https://github.com/infermedica/component-library/compare/develop...releases/v1.11.0#diff-e4bea14483c3a87f568f92973fb4a5d727252c4628b7ed69ca2f8beede906afe) depending on personal path where `Component Library` is stored.
I haven't found any other way in documentation to achieve this, `vueDocs.parse(path)` seems to push to `sourceFiles` just the `path` without any modification, while requiring `absolutePath`, so the only other way for "fix" I see here is running this script in CI instead of locally, but that's significantly bigger scope.
Running `pnpm release`
- [✅] My code follows the style …
> feat: remove personal paths from generated docs

- src/components/organisms/UiMultipleChoices/UiMultipleChoices.vue
- src/utilities/helpers/index.ts
- src/utilities/helpers/isSafariOnIOS/index.ts
Add checking if browser is Safari on IOS function
Add `scrollIntoView` for Safari on IOS
MGPFE-312
Closes #
To solve problem with auto scroll to the first invalid radio
In project MGP
Safari on IOS
https://github.com/user-attachments/assets/33e9c3fc-da3c-455f-a00d-0fd8f81af5b1
Safari:
https://github.com/user-attachments/assets/265b7692-65eb-4269-9350-f0b344ce3138
Chrome:
https://github.com/user-attachments/assets/64de3d51-dfe6-4458-80f0-0e52fd8a642a
> fix: scroll to the first invalid radio for Safari on IOS (MGPFE-312)

- src/components/molecules/UiToggleButtonGroup/_internal/UiToggleButton.vue
> fix: UiToggleButton modelValue typing error (NOTICKET)

- src/components/atoms/UiButton/UiButton.vue
- src/components/organisms/UiMenu/_internal/UiMenuItem.vue
Added text-align var for button and overwrite it for ui-menu-item with `start`. This should prevent longer text from displaying as centered.
Closes #
> fix: change text align for menu content
