src/components/atoms/UiCheckbox/UiCheckbox.vue, src/components/atoms/UiInput/UiInput.vue, src/components/atoms/UiRadio/UiRadio.vue, src/components/atoms/UiRange/UiRange.vue, src/components/molecules/UiChip/UiChip.vue, src/components/molecules/UiDropdown/_internal/UiDropdownItem.vue, src/components/molecules/UiFormField/UiFormField.vue, src/components/molecules/UiHeader/UiHeader.vue, src/components/molecules/UiNumberStepper/UiNumberStepper.vue, src/components/molecules/UiPopover/UiPopover.vue
Close 
- use assertions instead interface to type default props
=> chore(ts): use type assertions for default props

.unit-test-results.json, src/components/organisms/UiMenu/UiMenu.vue, src/components/organisms/UiMenu/_internal/UiMenuItem.vue
Close
* fix the typo in name of `UiMenuItem` item
* remove unused styles from `UiMenuItem`
=> fix: typos in menu

src/components/organisms/UiMenu/UiMenu.stories.js
=> docs: adjust Menu As Side Panel stories to design

pnpm-lock.yaml, src/components/molecules/UiChip/UiChip.stories.js, src/components/molecules/UiChip/UiChip.vue, src/components/molecules/UiPopover/UiPopover.vue, src/components/organisms/UiMenu/UiMenu.vue, src/components/organisms/UiMenu/_internal/UiMenuItem.vue, src/components/organisms/UiMenu/_internal/UiMenuItemSuffix.vue
Close #38 
- change border radius of the chip’s to `--border-radius-form` token
- increase size of pointer target area for remove button (32px x 32px)
- remove button placed in upper corner when chip has several lines
- button position after changes:
- pointer target area after changes:
=> feat: adjust UiChip to the new design

src/components/atoms/UiButton/UiButton.vue, src/components/atoms/UiInput/UiInput.vue, src/components/atoms/UiLink/UiLink.vue, src/components/atoms/UiRange/UiRange.vue, src/components/organisms/UiMenu/_internal/UiMenuItem.vue, src/composable/useActiveElement/index.ts, src/composable/useAttributes/index.ts, src/composable/useKeyValidation/index.ts, src/composable/useLink/index.ts, src/composable/useMutationObserver/index.ts
Close #34
- composables use typescript
- fix some ts errors
=> refactor: composables use ts

.unit-test-results.json, src/components/templates/UiQuestion/UiQuestion.spec.ts, src/components/templates/UiQuestion/UiQuestion.stories.js, src/components/templates/UiQuestion/UiQuestion.vue
Close
▪︎ Add `action: boolean` to issue settings to allow enable/disable `Report an issue` feature
* Add story `WithoutSkipThisQuestion`
=> refactor: extend question issue settings

.unit-test-results.json, src/composable/useMutationObserver/index.ts
=> fix: useMutationObserver cannot read $el of undefined

scripts/templates/component/component.vue
Related issue
Close #90  
- updated template for new components, using TypeScript for improved type checking and code maintainability.
=> refactor: update template for new components

src/components/atoms/UiCheckbox/UiCheckbox.vue, src/components/atoms/UiRadio/UiRadio.vue, src/components/atoms/UiRange/UiRange.vue, src/components/molecules/UiFormField/UiFormField.vue, src/components/molecules/UiInteractiveSvg/UiInteractiveSvg.vue, src/components/molecules/UiRating/UiRating.vue, src/components/molecules/UiScale/UiScale.vue, src/components/organisms/UiMultipleAnswer/_internal/UiMultipleAnswerItem.vue, src/components/organisms/UiSidePanel/UiSidePanel.vue, src/components/organisms/UiTabs/UiTabs.vue
Close #99 
- resolved TS errors in `UiScale`, `UiRating`, and `UiMultipleAnswerItem`
- fixed translation in `UiRating`
- removed unnecessary imports
=> fix: resolve ts errors

src/components/molecules/UiLoader/_internal/UiLoaderSpinner.vue, src/components/molecules/UiTile/UiTile.vue, src/components/organisms/UiAccordion/_internal/UiAccordionItem.vue, src/components/organisms/UiMultipleChoices/_internal/UiMultipleChoicesItem.vue
=> fix: squashed icon in UiLoader when label is multiline

src/components/organisms/UiDatepicker/UiDatepicker.stories.js, src/components/organisms/UiDatepicker/UiDatepicker.vue
Closes #128  
- Set proper font and letter spacing for datepicker label (body-2-comfortable)
=> fix: incorrect font datepicker label

src/components/organisms/UiMultipleAnswer/_internal/UiMultipleAnswerItem.vue
Close #178
* id is add to input element
=> fix: id doesn't work in UiMultipleAnswer

src/components/atoms/UiButton/UiButton.vue, src/components/atoms/UiLink/UiLink.vue
=> fix: typo in letter-spacing in small text button and link

src/components/molecules/UiBulletPoints/UiBulletPoints.vue
=> fix: icon props is not passed to UiBulletPoints

src/components/molecules/UiTile/UiTile.vue
=> fix: icon in UiTile is not centered horizontally

src/components/molecules/UiStepper/UiStepper.vue
=> fix: incorrect text style in mobile UiStepper

src/components/organisms/UiMultipleChoices/_internal/UiMultipleChoicesItem.vue
=> fix: incorrect gap between radio and label in UiMultipleChoicesItem

src/components/molecules/UiDropdown/useDropdownItems.ts
Closes #213 
- Update the class of the selected dropdown item
https://github.com/infermedica/component-library/assets/17556031/dba62230-ebb5-4e01-9ddc-fac2c001f6d7
=> fix: incorrect dropdown item focused

src/components/organisms/UiMultipleChoices/_internal/UiMultipleChoicesItem.vue
Closes #218  
- Fixes only issue on chromium-based browsers. Still, there is an issue with firefox.
https://github.com/infermedica/component-library/assets/17556031/8b132453-fc5a-454a-a193-4b37c0d7f36b
=> fix: voiceover issues for UiMultipleChoices component

.storybook/decorators/withVariants.js, .storybook/helpers/useArgTypes.js, .storybook/styles.scss, src/components/atoms/UiButton/UiButton.stories.ts, src/components/atoms/UiTextarea/UiTextarea.stories.ts
this PR solves problems with controls reactivity
=> fix: problems with controls addon reactivity

src/components/molecules/UiHeader/UiHeader.mdx, src/components/molecules/UiHeader/UiHeader.stories.js, src/components/molecules/UiHeader/UiHeader.vue
=> feat: add simple layout to header

.unit-test-results.json, components-api-lock.json, docs/releases/v0.7.x/v0.7.1/changelog.stories.mdx.mdx, package.json, src/components/organisms/UiSidePanel/UiSidePanel.vue
- change `flex-direction` and `justify-content` in the UiSidePanel's header part - keep consistency with the newest design; add css variables for these two properties as well
- change `align-self` of the UiSidePanel's close element; add css variable for this property
- add `padding-block` and `padding-inline` to the `close` part of the UiSidePanel; add `margin`, `display`, and `align-items` to the `label` of the UiSidePanel
https://github.com/infermedica/component-library/assets/13744352/9ba23d4f-046c-4521-8d46-29fb178233bc
=> feat/ui side panel header: new design 

src/components/atoms/UiCheckbox/UiCheckbox.vue, src/styles/variables/layouts.scss
Adjust UiCheckbox to new UUI design:
Import and use new token: `--border-radius-checkbox`
=> fix: change border-radius on UiCheckbox according to the newest design

docs/transition/transitions.stories.ts, src/components/atoms/UiButton/UiButton.stories.js, src/components/atoms/UiButton/UiButton.vue, src/components/molecules/UiLoader/UiLoader.vue, src/styles/mixins/states.scss
Add UiLoader to UiButton; 
Screens
=> feat: button with loader

src/components/organisms/UiContainer/UiContainer.vue
Link to component in Figma.
https://www.figma.com/file/2p8nMM7W88FU6r0kA52fAA/MGP-Component-Library?type=design&node-id=3158-80099&mode=design&t=Z3k3xSUjQOoOc2EJ-4
=> fix: change paddings on UiContainer according to the newest desing

src/components/templates/UiQuestion/UiQuestion.stories.js, src/components/templates/UiQuestion/UiQuestion.vue
Add description props to UiQuestion template.
=> feat: add description props to UiQuestion

src/components/organisms/UiList/_internal/UiListItem.vue, src/components/organisms/UiMultipleAnswer/UiMultipleAnswer.vue, src/components/organisms/UiMultipleChoices/UiMultipleChoices.vue, src/components/organisms/UiMultipleChoices/_internal/UiMultipleChoicesItem.vue
Fixed UiList paddings on mobile. Fix spacings on UiMultipleAnswer and UiMultipleChoice
=> fix: change spacings in UiMultiples components according to the newest designs

src/components/molecules/UiRating/UiRating.stories.js, src/components/molecules/UiRating/UiRating.vue
Allow to disable UiRating component
=> fix: cannot to disabled UiRating component

src/components/molecules/UiBulletPoints/UiBulletPoints.mdx, src/components/molecules/UiBulletPoints/UiBulletPoints.stories.js, src/components/molecules/UiBulletPoints/UiBulletPoints.vue, src/components/molecules/UiBulletPoints/_internal/UiBulletPointsItem.vue
We would like to have a small variant of UiBulletPointItem
=> feat: add UiBulletPointsItem small variant

src/components/molecules/UiFormField/UiFormField.vue, src/components/molecules/UiFormField/_internal/UiFormFieldCharacterCounter.vue
=> fix: adjust UiFormFieldCharacterCounter color to the design

src/components/atoms/UiTextarea/UiTextarea.stories.js, src/components/atoms/UiTextarea/UiTextarea.vue
add optional autogrowing to UiTextarea and fix a few issues
autogrowing textarea can't be resized
=> feat: optional autogrowing in UiTextarea

src/components/molecules/UiScale/UiScale.vue
=> fix: Change description color in UiScale component according to the newest design

src/components/organisms/UiCard/UiCard.vue
=> fix: Change padding in modern UiCard component according to the newest design

src/components/atoms/UiHeading/UiHeading.stories.js, src/components/atoms/UiHeading/UiHeading.vue
=> fix: default level of UiHeading should be 1 instead 2

src/components/atoms/UiButton/UiButton.stories.js, src/components/atoms/UiButton/UiButton.vue, src/components/atoms/UiIcon/UiIcon.vue, src/components/atoms/UiInput/UiInput.stories.js
- Add attribute `aria-hidden` for icons with default value
=> feat(a11y): hide svgs with decorative role for screen readers

.storybook/decorators/withVModel.ts, .storybook/helpers/getArgTypes.ts, src/components/atoms/UiButton/UiButton.stories.ts, src/components/atoms/UiButton/stories/Basic.vue, src/components/atoms/UiButton/stories/Circled.vue, src/components/atoms/UiButton/stories/Icon.vue, src/components/atoms/UiCheckbox/stories/Basic.vue, src/components/atoms/UiCheckbox/stories/Group.vue, src/components/atoms/UiHeading/stories/Basic.vue, src/components/atoms/UiIcon/UiIcon.stories.ts, src/components/atoms/UiIcon/stories/Basic.vue, src/components/atoms/UiInput/stories/Basic.vue, src/components/atoms/UiLink/stories/Basic.vue, src/components/atoms/UiLink/stories/Text.vue, src/components/atoms/UiProgress/UiProgress.stories.ts, src/components/atoms/UiProgress/stories/Basic.vue, src/components/atoms/UiProgress/stories/EvidenceBar.vue, src/components/atoms/UiRadio/UiRadio.stories.ts, src/components/atoms/UiRadio/stories/Basic.vue, src/components/atoms/UiRadio/stories/Group.vue, src/components/atoms/UiRange/stories/Basic.vue, src/components/atoms/UiText/stories/Basic.vue, src/components/atoms/UiTextarea/stories/Basic.vue
Fix warnings emitted by atoms stories
=> chore: fix warnings in atoms stories

src/components/molecules/UiDropdown/_internal/UiDropdownItem.vue
=> fix: UiDropdownItem typescript related bug (vue-tsc)

src/components/organisms/UiHorizontalPaging/UiHorizontalPaging.vue
Add missing import of UiHeading component in UiHorizontalPaging
=> fix: failed to resolve UiHeading in UiHorizontalPaging

scripts/create-release-changelog.mjs, scripts/release.mjs
**Related issue**
Closes #362 
**Scope of work**
Finish 'release` script as a commit with a version tag.
**Screenshots of visual changes**
No response
=> docs: commit files created by release script

.github/workflows/release.yaml, .github/workflows/storybook.yaml
**Related issue**
No response
**Scope of work**
Release CL on GH by GH Actions only from `main` branch
**Screenshots of visual changes**
No response
=> chore: update GH Actions for Release process

.github/workflows/check_vue_tsc.yml, .github/workflows/publish.yaml, .github/workflows/release.yaml, .github/workflows/storybook.yaml
**Related issue**
Closes #365 
**Scope of work**
Publish package on NPM after release package on GH
**Screenshots of visual changes**
No response
=> chore: publish on npm by GitHub Action

src/components/templates/UiQuestion/UiQuestion.vue
As it was triggering the URL change in the application, triggering the page reload.
=> fix: button submit in UiQuestion trigger default submit without prevention it

.github/workflows/update_develop_branch.yml
Add Github Action to update the `develop` branch after the release
Closes #372
=> chore: update develop branch github action

src/components/molecules/UiScale/UiScale.stories.js, src/components/molecules/UiScale/UiScale.vue
- Add/change aria-labels
- Add/change aria-labelledby
- Add aria-checked and role radio to UiRadio element
- Change default min and max value to more generic
https://infermedica.atlassian.net/wiki/spaces/DS/pages/4086923423/Scale
=> fix: accessibility improvements in UiScale component

src/components/atoms/UiCheckbox/UiCheckbox.vue, src/components/atoms/UiRadio/UiRadio.vue, src/components/organisms/UiMultipleAnswer/UiMultipleAnswer.stories.js, src/components/organisms/UiMultipleAnswer/UiMultipleAnswer.vue, src/components/organisms/UiMultipleAnswer/_internal/UiMultipleAnswerItem.vue
Add focus to first answer with error and add stories for this examples
We want to improve accessibility
In storybook
=> feat: add focus to first input with error in UiMultipleAnswer

src/components/organisms/UiList/_internal/UiListItem.vue, src/components/organisms/UiMultipleChoices/UiMultipleChoices.stories.js, src/components/organisms/UiMultipleChoices/UiMultipleChoices.vue, src/components/organisms/UiMultipleChoices/_internal/UiMultipleChoicesItem.vue
Add focus to first answer with error and add stories for this examples
We want to improve accessibility
In storybook
=> feat: add focus to first input with error in UiMultipleChoices

.github/workflows/release.yaml
GH Action release package without description
This PR should back to that
=> chore: incorporate the release pull request description as the body of the release

.storybook/main.ts, package.json, pnpm-lock.yaml
vite-plugin-vue-devtools in storybook
Closes #
=> chore: add vite-plugin-vue-devtools to storybook

.github/workflows/storybook.yaml
=> fix: failed storybook deploy

src/components/atoms/UiInput/UiInput.vue
=> feat: expose UiInput input template refs

src/components/atoms/UiTextarea/UiTextarea.vue
=> feat: expose UiTextarea textarea template refs

src/components/atoms/UiCheckbox/UiCheckbox.vue, src/components/atoms/UiRadio/UiRadio.vue, src/components/molecules/UiDropdown/UiDropdown.vue, src/components/molecules/UiTile/UiTile.vue, src/components/organisms/UiMultipleAnswer/UiMultipleAnswer.vue, src/components/organisms/UiMultipleChoices/UiMultipleChoices.vue
Remove parsing to JSON and use unchanged values in components
https://infermedica.atlassian.net/browse/MGPFE-199?atlOrigin=eyJpIjoiZGQzY2Q0ZTdiMTZiNGQwODkzNzdkNmY5Y2U1MmE3ZTUiLCJwIjoiaiJ9
=> fix: remove JSON's parsing from components

src/components/organisms/UiList/_internal/UiListItemPrefix.vue, src/components/organisms/UiList/_internal/UiListItemSuffix.vue
=> fix: imports in UiListItemSuffix and UiListItemPrefix

src/components/organisms/UiMenu/UiMenu.vue
=> fix: aliased import in UiMenu

.storybook/helpers/getArgTypes.ts
=> fix: remove quote's from getArgTypes props default values

.storybook/composable/useArgs.ts, .storybook/decorators/withVModel.ts, .storybook/helpers/getArgTypes.ts, src/components/organisms/UiHorizontalPaging/stories/MobileMenu.vue, src/components/organisms/UiHorizontalPaging/stories/Multilevel.vue, src/components/organisms/UiMenu/UiMenu.vue
=> fix: v-model issue in UiHorizontalPaging stories

src/components/templates/UiQuestion/UiQuestion.vue
Add missing spacer between actions in UiQuestion
Closes #
Before
After
=> fix: missing separator between actions in UiQuestion

src/components/organisms/UiHorizontalPaging/UiHorizontalPaging.vue, src/components/organisms/UiHorizontalPaging/_internal/UiHorizontalPagingItem.vue
Allow to set Links in UiHorizonralPagign as external links
Closes #
=> fix: menu item in horizontal paging as external link

.github/workflows/check_vue_tsc.yml, .github/workflows/storybook.yaml
update pnpm/action-setup to fix GH actions
Closes #
=> chore: update pnpm/action-setup to fix GH actions

src/components/organisms/UiMenu/stories/HasButton.vue
Adding aria-selected for option in listbox
https://infermedica.atlassian.net/browse/MGPFE-475
=> fix: add aria-selected for option in listbox

src/components/atoms/UiCheckbox/UiCheckbox.vue
Create variable border-radius-checkbox for MGP purpose
MGPFE-2127
Closes #
Fix border-radius for checkbox'es
=> fix: create variable border-radius-checkbox for MGP purpose

src/components/organisms/UiHorizontalPaging/UiHorizontalPaging.vue
Fix animation for HorizontalPaging
Closes #
=> fix: rtl animation for HorizontalPaging
